### PR TITLE
Bugfix/us23 run method

### LINKED ISSUE #40: Check of Sprint 1 outputs
Chris,
Checking outputs for Sprint 1 against user stories. All looks good except US 23, for duplicate name in GEDCOM file. Can you check if a duplicate name entry exists in the test file?

Thanks

### PR DESCRIPTION
**Pull request by CCorrado**
Fixes #40

### CODE REVIEW

**Comment by CCorrado** [comment]
@55Brian55  @jj1976  @rsukitha  I am about to head out, but the assignment is due at 10PM so i just want to check in and make sure these changes make it into the submission. I might not be back by 10.

**Comment by 55Brian55** [comment]
I reviewed it Chris and it looks good. Thanks for your help

**Comment by 55Brian55** [comment]
Chris, Jermaine, Sukitha
Assignment Sprint 1 is in!

**Comment by rsukitha** [comment]
Thanks Brian

**Pull request merged**
