### PR TITLE
Adding US01 and US02 changes

### PR DESCRIPTION
**Pull request by rsukitha**
Adding US01 - Dates Before Current Date #4 and US02 - Birth before marriage #3

### CODE REVIEW

**Comment by rsukitha** [comment]
The commit tab just shows 1 commit of "Added DocString" but the code in the Oull request has the change for US01 and US02 as well. I had created the branch with the codes for US01 and US02 in it already and hence you do not see a separate commit for the change.

**Comment by CCorrado** [comment]
Merge Conflicts

**Comment by CCorrado** [comment]
Hey @rsukitha  if you can look at my PR, #19 , I made some changes that look like they moved what you added docstrings to directly onto master. 

Once my PR gets merged, can you add your methods to a new feature branch and open a PR showing your changes? Its a little unclear right now with the conflicts

**Comment by rsukitha** [comment]
Sure I will look into it and keep you posted.

Thanks

**Pull request closed without merging**
