### PR TITLE
US10 Wrote a few unit tests to validate the marriage method.

### PR DESCRIPTION
**Pull request by CCorrado**
@jj1976 I found a few issues with the marriage validator. I don't think it was working as written, so I wrote a few unit tests that validated the method. Can you take a look?

### CODE REVIEW

**Comment by CCorrado** [comment]
Fixes #29

**Comment by jj1976** [comment]
sure,
let me check it

**Comment by jj1976** [comment]
I have updated the code and ran the unit test against a few dates. below is the output

ERROR: INDIVIDUAL: US10: jc: Jimmy /Connors/ is married but not at least 14 years old.
F.
======================================================================
FAIL: test_happy_path_husband (__main__.UserMarriageDateTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "UserMarriageDateTests.py", line 20, in test_happy_path_husband
    self.assertTrue(husband.validate_marriage(gedcom_data[0].get(family)))
AssertionError: False is not true

**Comment by jj1976** [comment]
i have also added the print statements for us07 and the test data file.

**Comment by jj1976** [comment]
Thanks Chris
let me know if i need to change anything.
I will create a test for 150 years method and verify as well with your sample tests.

**Pull request merged**
